version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: bank_app_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
